<?php

/**
 * Implements hook_menu()
 */
function entdisp_example_menu() {
  return array(
    'entdisp-example-form' => array(
      'page callback' => 'drupal_get_form',
      /* @see entdisp_example_form() */
      'page arguments' => array('entdisp_example_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function entdisp_example_form(array $form, array $form_state) {
  $form['plugin'] = array(
    '#type' => UIKIT_ELEMENT_TYPE,
    '#uikit_element_object' => entdisp()->etGetManager('node')->getUikitElementType(),
    '#default_value' => array(),
  );

  return $form;
}
