<?php

/**
 * Implements hook_menu()
 */
function entdisp_example_menu() {
  return array(
    'entdisp-example-form' => array(
      '#title' => 'Entdisp example form',
      'page callback' => 'drupal_get_form',
      /* @see entdisp_example_form() */
      'page arguments' => array('entdisp_example_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
    ),
    'node/%node/entdisp-example' => array(
      'page callback' => 'drupal_get_form',
      'title' => 'Entdisp example',
      /* @see entdisp_example_form() */
      'page arguments' => array('entdisp_example_node_demo_form', 1),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
    ),
  );
}

/**
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function entdisp_example_form(array $form, array $form_state) {

  $form['plugin'] = entdisp()->etGetDisplayManager('node')->confGetForm(array());

  return $form;
}

/**
 * @param array $form
 * @param array $form_state
 * @param object $node
 *
 * @return array
 */
function entdisp_example_node_demo_form(array $form, array $form_state, $node) {

  if (isset($_GET['plugin'])) {
    $settings = $_GET['plugin'];
  }
  elseif (isset($form_state['values']['plugin'])) {
    $settings = $form_state['values']['plugin'];
  }
  else {
    $settings = array();
  }

  $displayManager = entdisp()->etBundleGetDisplayManager('node', $node->type);

  $form['plugin'] = $displayManager->confGetForm($settings);

  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Show'),
  );
  $form['actions']['submit_invalid'] = array(
    '#type' => 'submit',
    '#value' => t('Submit invalid.'),
  );

  if ($settings) {
    $entityDisplay = $displayManager->confGetEntityDisplay($settings);
    $form['demo'] = array(
      '#type' => 'fieldset',
      '#title' => t('Node displayed with this display plugin.'),
      'content' => $entityDisplay->buildEntity('node', $node),
    );
  }

  return $form;
}

/**
 * @param array $form
 * @param array $form_state
 */
function entdisp_example_node_demo_form_validate(array &$form, array &$form_state) {
  if ('edit-submit-invalid' === $form_state['triggering_element']['#id']) {
    form_set_error('submit_invalid', t('The form was intentionally submitted as invalid.'));
  }
}

/**
 * @param array $form
 * @param array $form_state
 */
function entdisp_example_node_demo_form_submit(array &$form, array &$form_state) {
  $options['query']['plugin'] = $form_state['values']['plugin'];
  drupal_goto($_GET['q'], $options);
}
