<?php

use Drupal\entdisp\Hub\EntdispHub;

define('ENTDISP_PLUGIN_KEY', 'entity_display_plugin');
define('ENTDISP_ENTITYREFERENCE_FORMATTER', 'entdisp_entityreference');

require_once __DIR__ . '/entdisp.field.inc';

/**
 * Implements hook_views_api().
 *
 * @see entdisp_views_plugins()
 */
function entdisp_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Dependency injection container
 *
 * @return \Drupal\entdisp\Hub\EntdispHubInterface
 */
function entdisp() {
  static $hub;
  return isset($hub)
    ? $hub
    : $hub = EntdispHub::create();
}
