<?php

require_once __DIR__ . '/entdisp.field.inc';

/**
 * Implements hook_views_api().
 *
 * @see entdisp_views_plugins()
 */
function entdisp_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Dependency injection container
 *
 * @return \Drupal\entdisp\EntdispHub
 */
function entdisp() {
  static $services;
  return isset($services)
    ? $services
    : $services = new \Drupal\entdisp\EntdispHub();
}
